FROM ubuntu:xenial

## Setup essential

RUN \
               apt-get update \
       &&  apt-get install -y \
                       clang \
                       cmake \
                       git \
                       make \
                       python3 \
                       libncurses5-dev \
                       libncursesw5-dev
